### ISSUE TITLE
Expected the total count to be greater than the threshold count

### ISSUE THREAD

**Issue by dovancao** [shanewholloway/js-shamir-tss-gf256#2]
Hi there,
I'm new on javascipt. when I find some Shamir's Secret Sharing. I found your library and used it.
But I got this issue. Can you help me, please?
Thank you so much

As my image:
- secret  213213213
- thresholdShares  3
- totalShares  10
But I got error:
```
Expected the total count to be greater than the threshold count
```

![a0aab8f9634a00f86a4f43d08e465144](https://user-images.githubusercontent.com/36324165/48540239-24ac5600-e8ec-11e8-860d-e4a455fa0f25.png)

**Comment by shanewholloway** [comment]
Are you using v0.5.0?

What does [example.js](https://github.com/shanewholloway/js-shamir-tss-gf256/blob/master/docs/example.js) output for you?  

I also published [a tiny GitHub page](https://shanewholloway.github.io/js-shamir-tss-gf256/) so you can play with this module in your browser. Putting the following in the console does the right thing for me:

```javascript
let secret = new Uint8Array([2, 1, 3, 2, 1, 3, 2, 1, 3])

let shares = shamir_tss.generateShares_b64(secret, 3, 10)
```

**Comment by dovancao** [comment]
Thank Shane.
I just wondering that if my input is "interger" or "hex" string or something else. It must be converted to Uint8Array, Right?

**Comment by dovancao** [comment]
Thank you so much. I found my problem. Because my totalshare and threshold share is string

**Comment by shanewholloway** [comment]
Yes, the Galois field operates on an array of Uint8 values.  Happy to help!
